POST https://localhost:8001/datarecord

###
POST https://localhost:8001/datarecord
Content-Type: application/json
Authorization: Basic dummy:passwd

{
    "recordIdentifier" : "Jupiter",
    "recordDescription": "Notes about Jupiter during observation",
    "recordPayload": "Jupiter great red spot noticed, no changes related to previousobservation",
    "recordRightAscension" : "05h 11m 42s",
    "recordDeclination": "+22° 15' 54\""
}

###
GET https://localhost:8001/datarecord
Authorization: Basic dummy:passwd

###
DELETE https://localhost:8001/datarecord

###
POST https://localhost:8001/registration
Content-Type: application/json

{
    "username": "user2",
    "password": "password2",
    "email": "new email",
    "userNickname": "ninin"
}

###
GET https://localhost:8001/datarecord
Authorization: Basic user2:password2

###
GET https://localhost:8001

###
POST https://localhost:8001/datarecord
Content-Type: application/json
Authorization: Basic user2:password2

{
    "recordRightAscension":{},
    "recordPayload":{},
    "recordDeclination":0.5654151282359118,
    "recordDescription":{},
    "recordIdentifier":0.8177455329831433
}

###
POST https://localhost:8001/datarecord
Content-Type: application/json
Authorization: Basic user2:password2

{
"recordRightAscension":"4h 14m 33s",
"recordPayload":{},
"recordDeclination":"+15° 45' 2\"",
"recordDescription":{},
"recordIdentifier":{}
}

###
GET https://localhost:8001/search
Authorization: Basic user2:password2