POST https://localhost:8001/datarecord

###
POST https://localhost:8001/datarecord
Content-Type: text/plain
Authorization: Basic dummy:passwd

This is a message

###
GET https://localhost:8001/datarecord
Authorization: Basic dummy:passwd

###
DELETE https://localhost:8001/datarecord

###
POST https://localhost:8001/registration
Content-Type: text/plain

user2:password2

###
GET https://localhost:8001/datarecord
Authorization: Basic user2:password2

###
GET GET https://localhost:8001